[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
    "requests[socks]>=2.32.4",
    "stem>=1.8.2",
]
